In [ ]:
# Numpy
a = range(1000000)
b = range(1000000)
type(a)


range

In [ ]:
import time

In [ ]:
start = time.time()
c = []
for x,y in zip(a,b):
  su = x+y
  c.append(su)
end = time.time()
print('total time taken:',(end-start)*1000)
# time.time() measures the elapsed real world time

total time taken: 249.7706413269043


In [ ]:
import numpy as np

In [ ]:
start = time.time()
arr_a = np.array(a)
arr_b = np.array(b)
arr_c = arr_a + arr_b
end = time.time()
print('total time taken:',(end-start)*1000)

total time taken: 386.57641410827637


In [ ]:
a = np.array([1, 2, 3, 4, 5])
a.ndim # to get the dimension o array

1

In [ ]:
a.shape



(5,)

In [ ]:
a.dtype # to get the datatype

dtype('int64')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
arr2 = np.array([[1, 3, 5,7], [2, 4, 6, 8]])
arr2.ndim

2

In [ ]:
arr2.shape

(2, 4)

In [ ]:
print(list(range(1, 11)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
np.arange(1, 11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr3 = np.arange(5, 21)
print(arr3)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr3.reshape(4,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
arr3.reshape(2,8)

array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
arr = np.arange(16)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[7]

7

In [ ]:
arr = np.array([4, 1, 9, 3, 7, 3, 2])

In [ ]:
arr[4]

7

In [ ]:
arr[0]

4

In [ ]:
arr2 = np.array([[-7, 5, -2, 4],[5, 2, 7, 3], [10, -13, -3, 5]])
print(arr2)

[[ -7   5  -2   4]
 [  5   2   7   3]
 [ 10 -13  -3   5]]


In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2[2]


array([ 10, -13,  -3,   5])

In [ ]:
arr2[1,2]

7

In [ ]:
arr2[[1,2]]

array([[  5,   2,   7,   3],
       [ 10, -13,  -3,   5]])

In [ ]:
arr2[:,1]

array([  5,   2, -13])

In [ ]:
arr2[1:, 1:3]

array([[  2,   7],
       [-13,  -3]])

In [ ]:
arr2[1:3,[3,0]]

array([[ 3,  5],
       [ 5, 10]])

In [ ]:
len(arr3)

16

In [ ]:
arr3 = np.arange(10, 82, 2).reshape(6,6)
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [ ]:
arr3[:,[0,3]]

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [ ]:
arr3[:2,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [ ]:
arr3. mean(axis = 0)

array([40., 42., 44., 46., 48., 50.])

In [ ]:
arr3. mean(axis=1)

array([15., 27., 39., 51., 63., 75.])

In [ ]:
np.mean(arr3)

45.0

In [ ]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)
C = A.dot(B)
print(C)

[[28 34]
 [76 98]]


In [ ]:
C.T #transpose

array([[28, 76],
       [34, 98]])

In [ ]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
np.vstack((a,b)) #for vertical stacking

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [ ]:
np.concatenate((a,b)) # by default vertical stack and axis = 1 hstack

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])