In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn


In [ ]:
data = pd.read_csv('Iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
y = data['Species']
x = data.drop('Species', axis=1)

In [ ]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

Custom implementation

In [ ]:
x_mean = x-np.mean(x, axis=0)
x_mean

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -74.5      -0.743333         0.446      -2.358667     -0.998667
1   -73.5      -0.943333        -0.054      -2.358667     -0.998667
2   -72.5      -1.143333         0.146      -2.458667     -0.998667
3   -71.5      -1.243333         0.046      -2.258667     -0.998667
4   -70.5      -0.843333         0.546      -2.358667     -0.998667
..    ...            ...           ...            ...           ...
145  70.5       0.856667        -0.054       1.441333      1.101333
146  71.5       0.456667        -0.554       1.241333      0.701333
147  72.5       0.656667        -0.054       1.441333      0.801333
148  73.5       0.356667         0.346       1.641333      1.101333
149  74.5       0.056667        -0.054       1.341333      0.601333

[150 rows x 5 columns]

In [ ]:
cov_matrix = np.cov(x_mean.T)
cov_matrix

array([[ 1.88750000e+03,  2.57828859e+01, -7.49228188e+00,
         6.76677852e+01,  2.98322148e+01],
       [ 2.57828859e+01,  6.85693512e-01, -3.92684564e-02,
         1.27368233e+00,  5.16903803e-01],
       [-7.49228188e+00, -3.92684564e-02,  1.88004027e-01,
        -3.21712752e-01, -1.17981208e-01],
       [ 6.76677852e+01,  1.27368233e+00, -3.21712752e-01,
         3.11317942e+00,  1.29638747e+00],
       [ 2.98322148e+01,  5.16903803e-01, -1.17981208e-01,
         1.29638747e+00,  5.82414318e-01]])

In [ ]:
eigen_values, eigen_vectors = np.linalg.eigh(cov_matrix)
eigen_values

array([2.27360616e-02, 6.92908368e-02, 2.22994729e-01, 9.73286632e-01,
       1.89078098e+03])

In [ ]:
eigen_vectors = eigen_vectors.T
eigen_vectors

array([[-0.00170534,  0.28181947, -0.30753685, -0.44357483,  0.79324481],
       [ 0.00497451,  0.6110462 , -0.54687614, -0.19490229, -0.53808678],
       [ 0.00712756,  0.55014214,  0.77852879, -0.29611241, -0.05918769],
       [-0.04071433,  0.49432522, -0.01499187,  0.82236709,  0.2783389 ],
       [ 0.99913157,  0.01365776, -0.00396685,  0.0358369 ,  0.01579744]])

In [ ]:
idx = np.argsort(eigen_values)[::-1]
idx

array([4, 3, 2, 1, 0])

In [ ]:
eigenvalues = eigen_values[idx]
eigenvalues

array([1.89078098e+03, 9.73286632e-01, 2.22994729e-01, 6.92908368e-02,
       2.27360616e-02])

In [ ]:
eigen_vectors = eigen_vectors[idx]
eigen_vectors

array([[ 0.99913157,  0.01365776, -0.00396685,  0.0358369 ,  0.01579744],
       [-0.04071433,  0.49432522, -0.01499187,  0.82236709,  0.2783389 ],
       [ 0.00712756,  0.55014214,  0.77852879, -0.29611241, -0.05918769],
       [ 0.00497451,  0.6110462 , -0.54687614, -0.19490229, -0.53808678],
       [-0.00170534,  0.28181947, -0.30753685, -0.44357483,  0.79324481]])

In [ ]:
explained_variance_custom = eigenvalues/np.sum(eigenvalues)
explained_variance_custom

array([9.99319101e-01, 5.14403271e-04, 1.17857591e-04, 3.66217226e-05,
       1.20165058e-05])

In [ ]:
np.cumsum(explained_variance_custom)

array([0.9993191 , 0.9998335 , 0.99995136, 0.99998798, 1.        ])

selecting 0.97 as our variance cut off. so, 2 principal components are selected.

In [ ]:
principal_comp = eigen_vectors[:2]
principal_comp

array([[ 0.99913157,  0.01365776, -0.00396685,  0.0358369 ,  0.01579744],
       [-0.04071433,  0.49432522, -0.01499187,  0.82236709,  0.2783389 ]])

In [ ]:
x_new_custom = np.dot(x_mean, principal_comp.T)
x_new_custom

array([[-7.45475269e+01,  4.41425501e-01],
       [-7.35491434e+01,  3.09342060e-01],
       [-7.25571205e+01,  8.45275987e-02],
       [-7.15517906e+01,  1.60353347e-01],
       [-7.05527631e+01,  2.27636455e-01],
       [-6.95354479e+01,  6.82532551e-01],
       [-6.85575899e+01, -2.06900363e-02],
       [-6.75509913e+01,  1.90728535e-01],
       [-6.65616547e+01, -2.21321702e-01],
       [-6.55544836e+01,  3.65310173e-02],
       [-6.45493236e+01,  2.61818058e-01],
       [-6.35536129e+01,  1.12428635e-02],
       [-6.25616417e+01, -2.15782028e-01],
       [-6.15800901e+01, -7.50369097e-01],
       [-6.05592753e+01,  4.54831204e-02],
       [-5.95491857e+01,  2.51717420e-01],
       [-5.85593354e+01, -9.42719598e-02],
       [-5.75607105e+01, -2.22884291e-01],
       [-5.65438233e+01,  2.75209069e-01],
       [-5.55600537e+01, -2.26573813e-01],
       [-5.45496505e+01,  2.36456947e-02],
       [-5.35598142e+01, -2.78669404e-01],
       [-5.25881927e+01, -1.03189848e+00],
       [-5.